zuul:
  routes:
    demo:
      path: /demo-filter
server:
  port: 8090

spring:
  application:
    name: zuul-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka